# Project information
site_name: CLOUDACODE - cloud, devops, kubernetes, and cncf
site_url: https://cloudacode.github.io/tutorials/
site_author: KC Chang

# Repository
repo_name: cloudacode/tutorials
repo_url: https://github.com/cloudacode/tutorials
edit_uri: ""

# Configuration
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.highlight

# Page tree
nav:
  - Home: index.md
  - Tutorial:
    - Cloud:
      - AWS:
        - cloud/aws/ec2-setup.md
        - cloud/aws/apache-tomcat-redis.md
      - GCP:
        - cloud/gcp/gcp-ce-setup.md
    - Python:
      - python/flask/simple-flask-app.md
  #   - DevOps(CI/CD):
  #   - DevOps(Terraform):
  #   - Kubernetes:
  #   - Monitoring: 
  #   - CNCF:
  #   - ETC:
  - Blog ⧉: https://medium.com/@cloudacode
  - PodCast ⧉: https://www.podbbang.com/channels/1779436
