# Project information
site_name: CLOUDACODE - get started with step-by-step tutorials
site_url: https://cloudacode.com/tutorials/
site_author: KC Chang

# Repository
repo_name: cloudacode/tutorials
repo_url: https://github.com/cloudacode/tutorials
edit_uri: ""

# Configuration
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight

# Page tree
nav:
  - Home: index.md
  - Tutorial:
    - Cloud:
      - AWS:
        - cloud/aws/ec2-setup.md
        - cloud/aws/apache-tomcat-redis.md
      - GCP:
        - cloud/gcp/gcp-ce-setup.md
    - Python:
      - python/flask/simple-flask-app-mariadb.md
    - DevOps:
      - CICD:
        - devops/cicd/github-aws-codebuild-dockerhub.md
  #   - DevOps(Terraform):
  #   - Kubernetes:
  #   - Monitoring: 
  #   - CNCF:
  #   - ETC:
  - Blog ⧉: https://medium.com/@cloudacode
  - Youtube ⧉: https://www.youtube.com/channel/UCw46J_QQ3-HrjPsSsuOSDdQ
